### ISSUE TITLE
Using `tilesets status` for an invalid tileset id throws an error

### ISSUE THREAD

**Issue by jseppi** [mapbox/tilesets-cli#112]
Here's an excerpt from stack trace, showing what I think is the most important part:

```
$ pipenv run tilesets status jseppimbx.fake-id
Loading .env environment variables…
Traceback (most recent call last):
  ...
  File "/<...>/lib/python3.8/site-packages/mapbox_tilesets/scripts/cli.py", line 245, in status
    status["id"] = job["tilesetId"]
TypeError: string indices must be integers
```

**Comment by Gerdie** [comment]
Deliberately throwing these errors in: https://github.com/mapbox/tilesets-cli/pull/145

new behavior:
```
tilesets status mariamoy.notreal
Traceback (most recent call last):
  File "/Users/mariamoy/tilesets-cli/.env3/bin/tilesets", line 11, in <module>
    load_entry_point('mapbox-tilesets', 'console_scripts', 'tilesets')()
  File "/Users/mariamoy/tilesets-cli/.env3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mariamoy/tilesets-cli/.env3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/mariamoy/tilesets-cli/.env3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/mariamoy/tilesets-cli/.env3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mariamoy/tilesets-cli/.env3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/mariamoy/tilesets-cli/mapbox_tilesets/scripts/cli.py", line 253, in status
    raise errors.TilesetsError(r.text)
mapbox_tilesets.errors.TilesetsError: {"message":"mariamoy.notreal does not exist."}
```
