### ISSUE TITLE
Error installing on mac os 11.1 (20C69) with python 3.9.1

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/tilesets-cli#123]
Here's the installation output:
<details>
```
pip install mapbox-tilesets
Collecting mapbox-tilesets
  Downloading mapbox_tilesets-1.5.1-py3-none-any.whl (14 kB)
Collecting jsonschema~=3.0
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 1.1 MB/s
Collecting click~=7.1.2
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 984 kB/s
Collecting cligj
  Downloading cligj-0.7.1-py3-none-any.whl (7.1 kB)
Collecting supermercado~=0.2.0
  Downloading supermercado-0.2.0-py3-none-any.whl (8.1 kB)
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 1.4 MB/s
Collecting jsonseq~=1.0
  Downloading jsonseq-1.0.0-py3-none-any.whl (4.6 kB)
Collecting mercantile~=1.1.6
  Downloading mercantile-1.1.6-py3-none-any.whl (13 kB)
Collecting requests-toolbelt
  Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
     |████████████████████████████████| 54 kB 1.9 MB/s
Collecting boto3
  Downloading boto3-1.16.60-py2.py3-none-any.whl (130 kB)
     |████████████████████████████████| 130 kB 331 kB/s
Collecting attrs>=17.4.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 1.3 MB/s
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.17.3.tar.gz (106 kB)
     |████████████████████████████████| 106 kB 303 kB/s
Requirement already satisfied: setuptools in /Users/saman/.pyenv/versions/3.9.1/lib/python3.9/site-packages (from jsonschema~=3.0->mapbox-tilesets) (49.2.1)
Collecting six>=1.11.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting numpy
  Downloading numpy-1.19.5.zip (7.3 MB)
     |████████████████████████████████| 7.3 MB 2.6 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting rasterio
  Downloading rasterio-1.2.0.tar.gz (2.2 MB)
     |████████████████████████████████| 2.2 MB 4.8 MB/s
  Installing build dependencies ... -	       done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/saman/.pyenv/versions/3.9.1/bin/python3.9 /Users/saman/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/tmphx0ay6ro
       cwd: /private/var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/pip-install-vm_vmnfz/rasterio
  Complete output (23 lines):
  init_dgelsd failed init
  Traceback (most recent call last):
    File "/Users/saman/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/Users/saman/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/saman/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/private/var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/pip-build-env-3y4j20oj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 149, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/private/var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/pip-build-env-3y4j20oj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/private/var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/pip-build-env-3y4j20oj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/pip-build-env-3y4j20oj/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 74, in <module>
      import numpy as np
    File "/private/var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/pip-build-env-3y4j20oj/overlay/lib/python3.9/site-packages/numpy/__init__.py", line 286, in <module>
      raise RuntimeError(msg)
  RuntimeError: Polyfit sanity test emitted a warning, most likely due to using a buggy Accelerate backend. If you compiled yourself, see site.cfg.example for information. Otherwise report this to the vendor that provided NumPy.
  RankWarning: Polyfit may be poorly conditioned

  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/saman/.pyenv/versions/3.9.1/bin/python3.9 /Users/saman/.pyenv/versions/3.9.1/lib/python3.9/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /var/folders/2r/9pqzq3q97w32hrk6lthf816w0000gq/T/tmphx0ay6ro Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 21.0 is available.
You should consider upgrading via the '/Users/saman/.pyenv/versions/3.9.1/bin/python3.9 -m pip install --upgrade pip' command.
```
</details>

looks like `rasterio` installation fails.

**Comment by sgillies** [comment]
@samanpwbb I think this maybe be related to https://github.com/pypa/pip/issues/9138. The Python 3.9.1 release notes also mention a problem with pip at the time of the release: https://www.python.org/downloads/release/python-391/. As I understand it, the "*macosx_10_9*" binary packages of numpy and rasterio on PyPI are compatible with Python 3.9.1 on macOS (at least the one downloaded from python.org, YMMV with other builds) *but* pip versions before 20.3 resulted in a failed compatibility check.

Try upgrading pip to the latest 20.3.x or even 21.0 and see if that unblocks you.

cc @dnomadb

**Comment by samanpwbb** [comment]
Upgrading pip worked for me @sgillies - thanks!
