### ISSUE TITLE
`tilesets delete-source` is confusing and doesn't seem to work

### ISSUE THREAD

**Issue by ericfischer** [mapbox/tilesets-cli#124]
I just tried to delete a source:

```
(python-venv) ➤ tilesets delete-source enf mapbox://tileset-source/enf/onepoint
To confirm source deletion please enter the full source id "enf/mapbox://tileset-source/enf/onepoint": enf/mapbox://tileset-source/enf/onepoint
Traceback (most recent call last):
  File "/Users/enf/python-venv/bin/tilesets", line 11, in <module>
    load_entry_point('mapbox-tilesets', 'console_scripts', 'tilesets')()
  File "/Users/enf/python-venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/enf/python-venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/enf/python-venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/enf/python-venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/enf/python-venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/enf/tilesets-cli/mapbox_tilesets/scripts/cli.py", line 685, in delete_source
    raise errors.TilesetsError(r.text)
mapbox_tilesets.errors.TilesetsError: {"message":"Not Found"}
```

It threw an error, had a confusing interaction (wanted me to type `enf/mapbox://tileset-source/enf/onepoint` instead of the fully-qualified `mapbox://tileset-source/enf/onepoint`), and the source still seems to exist afterward:

```
(python-venv) ➤ tilesets list-sources enf
mapbox://tileset-source/enf/onepoint
…
```

**Comment by ericfischer** [comment]
What it actually wants is

```
(python-venv) ➤ tilesets list-sources enf
mapbox://tileset-source/enf/onepoint
…
(python-venv) ➤ tilesets delete-source enf onepoint
To confirm source deletion please enter the full source id "enf/onepoint": enf/onepoint
Source deleted.
```

**Comment by ericfischer** [comment]
Documentation fix in https://github.com/mapbox/tilesets-cli/pull/125
