### ISSUE TITLE
Syntax Error. Can't run or import.

### ISSUE THREAD

**Issue by gonesurfing** [mapbox/tilesets-cli#93]
me@macbook % tilesets                                                              
Traceback (most recent call last):
  File "/Users/me/opt/anaconda3/envs/pps/bin/tilesets", line 5, in <module>
    from mapbox_tilesets.scripts.cli import cli
  File "/Users/me/opt/anaconda3/envs/pps/lib/python2.7/site-packages/mapbox_tilesets/scripts/cli.py", line 121
    f"You can view the status of your tileset with the `tilesets status {tileset}` command.",

**Comment by gonesurfing** [comment]
Disregard. was in a python 2.7 environment.
